### ISSUE TITLE
make plot comparing 8 different methods for estimating functional connectomes

### ISSUE THREAD

**Issue by jovo** [openconnectome/f2g#1]
- corr
 - partial corr
 - cov
 - inv cov

for each, use raw values, and pass to ranks (you can use 'sort' in matlab).
use the CORR dataset, with the 788 ROI atlas

we plot 8 lines, 1 for each functional connectome estimate, for each, we plot 
1-MNR on y-axis and threshold on x-axis

@willgray @gkiar what do you guys think?

**Comment by jovo** [comment]
http://www.mathworks.com/help/stats/tiedrank.html 
to deal with tied ranks appropriately.

rank *before* thresholding

**Comment by ebridge2** [comment]
@jovo when assigning ranks... I would assume we want to compute over the whole matrix, and not column by column, of the metric being analyzed? Tiedrank does vector by vector. For example; we would want the matrix, [1 4 5; 2 3 4] to return [1 4.5  6; 2 3 4.5], yes? Tiedranks returns [1 2 2; 2 1 1] since it computes the rank per column. I'll just write a simple function that does that with the same handling of ties as tiedranks but computes over the entire nxn matrix

**Comment by jovo** [comment]
Right. You can just vectorize by x(:), then tied ranks, then vec2mat or
reshape

On Saturday, July 11, 2015, ebridge2 <notifications@github.com> wrote:

>  @jovo <https://github.com/jovo> when assigning ranks... I would assume
> we want to compute over the whole matrix, and not column by column, of the
> metric being analyzed? Tiedrank does vector by vector. For example; we
> would want the matrix, [1 4 5; 2 3 4] to return [1 4.5 6; 2 3 4.5], yes?
> Tiedranks returns [1 2 2; 2 1 1] since it computes the rank per column.
> I'll just write a simple function that does that with the same handling of
> ties as tiedranks but computes over the entire nxn matrix
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120665525>.
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
yep; sounds good

**Comment by jovo** [comment]
make sure to write some code to check and make sure your code is correct.
you can do that before or after applying it to the data,
usually before is better, but either is fine.

On Sat, Jul 11, 2015 at 6:28 PM, ebridge2 <notifications@github.com> wrote:

>  yep; sounds good
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120666098>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
one question: when we are computing inverse covariance, we will be looking at items (in general, especially with large numbers of rois) where we are making t time observations, each a vector of length n (the number of rois). When n > t, the result is singular, and therefore inverse covariance cannot effectively be computed. Should we just ignore inverse covariance for the large roi case? Or we could test a smaller number of rois.

**Comment by ebridge2** [comment]
@jovo, nvmd, that's why pinv was key.

**Comment by jovo** [comment]
Correct!

On Sunday, July 12, 2015, ebridge2 <notifications@github.com> wrote:

>  @jovo <https://github.com/jovo>, nvmd, that's why pinv was key.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120753714>.
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by jovo** [comment]
We will play with low rank approximations.
Do u know what that means?

On Sunday, July 12, 2015, joshua vogelstein <joshuav@gmail.com> wrote:

> Correct!
>
> On Sunday, July 12, 2015, ebridge2 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>>  @jovo <https://github.com/jovo>, nvmd, that's why pinv was key.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120753714>.
>>
>
>
> --
> the glass is all full:  half water, half air.
> openconnecto.me, jovo.me, office hours
> <https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>
>
>

-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
I understand the basics of the concept. As in, I understand that low-rank approximations involve using a lower rank matrix than the given matrix and measuring the difference between the two with some cost function, and optimizing the lower rank matrix with this cost function (this was briefly covered in a general machine learning basics course on coursera that I watched a few videos of just to get the idea).

**Comment by jovo** [comment]
cool.
the gilbert strang linear algebra course on MIT OCW is awesome.
it will explain it.
you got the basic idea already.
once you get the 8 lines we already discussed,
and some code demonstrating that all your functions are working as expected,
we can explore low-rank approximations :)


On Sun, Jul 12, 2015 at 3:32 PM, ebridge2 <notifications@github.com> wrote:

>  I understand the basics of the concept. As in, I understand that
> low-rank approximations involve using a lower rank matrix than the given
> matrix and measuring the difference between the two with some cost
> function, and optimizing the lower rank matrix with this cost function
> (this was briefly covered in a general machine learning basics course on
> coursera that I watched a few videos of just to get the idea).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120755739>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
Also, when defining partial correlation, I use the definition that the pcorr(i,j) = -pinvcorr(i,j)/(sqrt(pinvcorr(i,i)*pinvcorr(j,j)) given on wikipedia, where pcorr is the partial correlation and pinvcorr is the pseudo-inverse of the correlation matrix of the timeseries being analyzed. I had to write a custom function because the partialcorr function in matlab uses a regular inverse. That sounds good, right?

**Comment by ebridge2** [comment]
And yea, I have a test script that uses a 3x2x2 as our 'simulated' (roi)x(timesteps)x(numsubs)

**Comment by ebridge2** [comment]
I'll push that once I finish checking with a piece of paper and a calculator just to verify...

**Comment by jovo** [comment]
cool.  that all sounds right to me.

On Sun, Jul 12, 2015 at 3:37 PM, ebridge2 <notifications@github.com> wrote:

>  Also, when defining partial correlation, I use the definition that the
> pcorr(i,j) = -pinvcorr(i,j)/(sqrt(pinvcorr(i,i)*pinvcorr(j,j)) given on
> wikipedia, where pcorr is the partial correlation and pinvcorr is the
> pseudo-inverse of the correlation matrix of the timeseries being analyzed.
> I had to write a custom function because the partialcorr function in matlab
> uses a regular inverse. That sounds good, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120755974>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
test_scripts includes some basic tests for the functions. I did not bother to test the inverse covariance since assuming I am using pinv correctly the rest of the code is exactly identical to the covariance, and I do not know how to compute pinv manually so there isn't really much to test there. Will be writing up a batch script for the CIS cluster and the tests will be up in the next thirty minutes or so, with outputs and a graph within 5 hours depending on processing time (SWU is a bit slow... takes like 20-30 min per iteration and there will be 8)

**Comment by jovo** [comment]
make a folder called 'tests' or something,
and put 1 test script in there per function that you are testing.

make another folder called 'experiments'
and put 1 script in there per experiment you conduct.
i'm thinking something like specifying the parameters, generating simulated
data, and checking whether the estimates are close to the truth,
and providing some numerical score indicating that they are close,
or at least that they are getting close as T increases, or something like
that...

On Sun, Jul 12, 2015 at 4:18 PM, ebridge2 <notifications@github.com> wrote:

>  test_scripts includes some basic tests for the functions. I did not
> bother to test the inverse covariance since assuming I am using pinv
> correctly the rest of the code is exactly identical to the covariance, and
> I do not know how to compute pinv manually so there isn't really much to
> test there. Will be writing up a batch script for the CIS cluster and the
> tests will be up in the next thirty minutes or so, with outputs and a graph
> within 5 hours depending on processing time (SWU is a bit slow... takes
> like 20-30 min per iteration and there will be 8)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120759173>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
for the experiments, we could do something where we have known inputs and a known output for each measure (correlation, partial correlation, covariance, inverse covariance). We could then add normally distributed noise over some decreasing range and verify that as the range of the noise decreases the norm btwn the output matrix and the expected decreases as well?

**Comment by ebridge2** [comment]
does that sound like a decent verification experiment?

**Comment by jovo** [comment]
yup, the two reasonable options are:

1) error decreases with T increasing
2) error decreases with sigma^{-1} increasing

i find #1 more useful typically, but both are good...

On Sun, Jul 12, 2015 at 5:42 PM, ebridge2 <notifications@github.com> wrote:

>  does that sound like a decent verification experiment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120763805>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
what is T in this case exactly?

**Comment by jovo** [comment]
number of time steps

On Sun, Jul 12, 2015 at 5:53 PM, ebridge2 <notifications@github.com> wrote:

>  what is T in this case exactly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120765622>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
ah okay, so the simulated data could be something like zero centered noise of length T?

**Comment by ebridge2** [comment]
actually nevermind. I have an idea of what to do.

**Comment by jovo** [comment]
yup.  multivariate gaussian, zero mean, covariance specified by you.
let's consider a few test cases:

1) C = 2*eye(d).
2) C =  ones(d)+eye(d)
3) same as 2, but zero out one of the off diagonals (ie,
C(end,1)=C(1,end)=0)
4) same, but zero out another

we'll able to understand the impact of T and sparsity on estimation error.

for error, in each case, we probably want something like:

norm(Cest-C,'fro')/norm(C,'fro')


On Sun, Jul 12, 2015 at 5:59 PM, ebridge2 <notifications@github.com> wrote:

>  ah okay, so the simulated data could be something like zero centered
> noise of length T?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120766967>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
@jovo do you have time tomorrow at any point and we can discuss the relevance of what those experiments will do? I think I see what process you want to use, but I'm unsure as to how they will help us probably due to my lack of a statistics background. Maybe a 15 min overview or something?

**Comment by jovo** [comment]
yup.  anytime in the afternoon is fine.  just holler.

On Mon, Jul 13, 2015 at 12:18 AM, ebridge2 <notifications@github.com> wrote:

>  @jovo <https://github.com/jovo> do you have time tomorrow at any point
> and we can discuss the relevance of what those experiments will do? I think
> I see what process you want to use, but I'm unsure as to how they will help
> us probably due to my lack of a statistics background. Maybe a 15 min
> overview or something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120805509>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
cool. maybe 2ish or so?

**Comment by jovo** [comment]
sure.

On Mon, Jul 13, 2015 at 12:21 AM, ebridge2 <notifications@github.com> wrote:

>  cool. maybe 2ish or so?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/1#issuecomment-120806632>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
think we're done here...
