### ISSUE TITLE
generate plots demonstrating that 3 connectome estimates are working as they should (in R)

### ISSUE THREAD

**Issue by jovo** [openconnectome/f2g#20]
- thresholding
- ptiles
- nbin* of rank

@gkiar you'll need to think of a convincing numerical example, where we know what the answer should be (perhaps visually or numerically by hand).  i recommend using a simulation with a very small sample size and number of vertices, eg, 3 vertices, 2 samples & 2 subjects.

**Comment by gkiar** [comment]
yup. I've written much of this locally to test. will commit it.

--
Greg Kiar <gkiar07@gmail.com>

On Wed, Aug 26, 2015 at 6:43 PM, joshua vogelstein <notifications@github.com
