### ISSUE TITLE
add dcorr to the list of methods for estimating relationship between ROIs

### ISSUE THREAD

**Issue by jovo** [openconnectome/f2g#3]
the R package energy has code.
you can port it to matlab, 
run it in R,
or ask me for matlab code, and i can get it for you.
but better to try to figure it out for yourself first.

**Comment by ebridge2** [comment]
dcorr = the distance correlation?

**Comment by jovo** [comment]
yah, there are a bunch of articles on it that are impossible to understand.
but the algorithm is simple enough.
and i can provide the intuition.

On Mon, Jul 13, 2015 at 12:37 AM, ebridge2 <notifications@github.com> wrote:

>  dcorr = the distance correlation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/3#issuecomment-120810854>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ebridge2** [comment]
do we still want to do this?

**Comment by jovo** [comment]
nope.

On Fri, Jul 17, 2015 at 2:41 PM, ebridge2 <notifications@github.com> wrote:

>  do we still want to do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/f2g/issues/3#issuecomment-122370198>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>
